# Generated by Django 5.2.5 on 2026-05-14 15:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('habilidades_blandas', models.TextField(blank=True)),
                ('estado_contrato', models.CharField(choices=[('activo', 'Activo'), ('finiquitado', 'Finiquitado'), ('renovado', 'Renovado')], default='activo', max_length=20)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='certificados/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='main.empleado')),
            ],
        ),
    ]
